server:
  port: ${PORT:8762}

logging:
    level:
        root: WARN
        com.elderbyte: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server-web.discoverd:8080/eureka/}
  instance:
      preferIpAddress: true
