info:
  component: Turbine

PREFIX:

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: ${PORT:8989}

logging:
    level:
        root: WARN
        com.elderbyte: INFO


turbine:
  aggregator:
    clusterConfig: ${CLUSTER_LIST}
  appConfig: ${SERVICE_LIST}


_clusterNameExpression: "'default'"

eureka:
  client:
    healthcheck.enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server-web.discoverd:8080/eureka/}
  instance:
      preferIpAddress: true
